import type { WorkroomData } from "./types";

export const sampleData: WorkroomData = {
  goals: [
    {
      id: "goal-germany-study",
      goalTitle: "Prepare for German study abroad application",
      area: "Long Term",
      whyItMatters:
        "This is the main life direction tying language study, documents, savings, portfolio, and school research together.",
      targetDate: "2027-03-01",
      currentStage: "Active",
      nextMilestone: "Finish LMU and uni-assist document checklist before the July review week.",
      progressPercentage: 34,
      importance: 10,
      linkedProjectIds: ["project-portfolio-site", "project-upwork-profile"],
      linkedTaskIds: ["action-lmu-docs", "action-german-review", "action-portfolio-wireframe"],
      linkedMoneyRecordIds: ["money-study-saving-1", "money-goethe-book"],
      linkedDocumentIds: ["admin-lmu-docs", "admin-uni-assist"],
    },
    {
      id: "goal-german-b2",
      goalTitle: "German A1 to B2 for study abroad",
      area: "Language",
      whyItMatters:
        "German level affects school options, visa confidence, daily life, and the strength of the application story.",
      targetDate: "2026-12-20",
      currentStage: "Building",
      nextMilestone: "Complete A1 grammar correction loop and start A2 listening diary.",
      progressPercentage: 18,
      importance: 9,
      linkedProjectIds: [],
      linkedTaskIds: ["action-german-review"],
      linkedMoneyRecordIds: ["money-goethe-book"],
      linkedDocumentIds: [],
    },
    {
      id: "goal-portfolio-career",
      goalTitle: "Build a portfolio that can support jobs and freelance work",
      area: "Portfolio",
      whyItMatters:
        "Portfolio quality connects design school, employment, Upwork, and long-term creative independence.",
      targetDate: "2026-09-15",
      currentStage: "Active",
      nextMilestone: "Publish the first website version with DOLLSET, NACRE ROOM, and NAYUL OS case studies.",
      progressPercentage: 42,
      importance: 10,
      linkedProjectIds: [
        "project-portfolio-site",
        "project-dollset",
        "project-nacre-room",
        "project-nayul-os",
        "project-upwork-profile",
      ],
      linkedTaskIds: ["action-portfolio-wireframe", "action-dollset-case", "action-upwork-draft"],
      linkedMoneyRecordIds: ["money-domain"],
      linkedDocumentIds: ["admin-portfolio-assets"],
    },
    {
      id: "goal-freelance-income",
      goalTitle: "Create an overseas freelance income route",
      area: "Career",
      whyItMatters:
        "Freelance income can support study abroad savings and prove international design communication.",
      targetDate: "2026-10-31",
      currentStage: "Planning",
      nextMilestone: "Launch Upwork profile with three portfolio services and one test proposal.",
      progressPercentage: 22,
      importance: 8,
      linkedProjectIds: ["project-upwork-profile", "project-portfolio-site"],
      linkedTaskIds: ["action-upwork-draft"],
      linkedMoneyRecordIds: ["money-upwork-income"],
      linkedDocumentIds: ["admin-upwork-account"],
    },
    {
      id: "goal-study-abroad-savings",
      goalTitle: "Build study abroad preparation fund",
      area: "Money",
      whyItMatters:
        "Savings decide how much freedom there is for language exams, documents, applications, and moving costs.",
      targetDate: "2027-02-15",
      currentStage: "Active",
      nextMilestone: "Reach 30 percent of the first preparation fund target.",
      progressPercentage: 26,
      importance: 9,
      linkedProjectIds: ["project-upwork-profile"],
      linkedTaskIds: ["action-money-audit"],
      linkedMoneyRecordIds: ["money-study-saving-1", "money-subscription", "money-upwork-income"],
      linkedDocumentIds: [],
    },
    {
      id: "goal-content-system",
      goalTitle: "Post design process content consistently",
      area: "Content",
      whyItMatters:
        "SNS content can document taste, attract freelance trust, and make the portfolio process visible.",
      targetDate: "2026-08-30",
      currentStage: "Building",
      nextMilestone: "Post three process notes: DOLLSET, German study desk, and NAYUL OS workflow.",
      progressPercentage: 31,
      importance: 7,
      linkedProjectIds: ["project-dollset", "project-nayul-os"],
      linkedTaskIds: ["action-sns-upload"],
      linkedMoneyRecordIds: [],
      linkedDocumentIds: [],
    },
  ],
  todayActions: [
    {
      id: "action-german-review",
      actionTitle: "Review 30 German A1 sentences and mark weak verb positions",
      linkedGoalId: "goal-german-b2",
      linkedProjectId: "",
      area: "Language",
      priority: "High",
      importance: 9,
      estimatedTime: "45 min",
      energyLevel: "medium",
      dueDate: "2026-06-30",
      status: "Today",
      whyThisMatters: "This keeps the German A1 to B2 route moving and supports the study abroad goal.",
    },
    {
      id: "action-lmu-docs",
      actionTitle: "Check LMU and uni-assist document gaps",
      linkedGoalId: "goal-germany-study",
      linkedProjectId: "",
      area: "Life Admin",
      priority: "Critical",
      importance: 10,
      estimatedTime: "30 min",
      energyLevel: "low",
      dueDate: "2026-07-02",
      status: "Today",
      whyThisMatters: "Document uncertainty is the biggest hidden risk in the Germany route.",
    },
    {
      id: "action-portfolio-wireframe",
      actionTitle: "Create portfolio website case-study order and first section wireframe",
      linkedGoalId: "goal-portfolio-career",
      linkedProjectId: "project-portfolio-site",
      area: "Portfolio",
      priority: "High",
      importance: 10,
      estimatedTime: "70 min",
      energyLevel: "high",
      dueDate: "2026-07-03",
      status: "In Progress",
      whyThisMatters: "The portfolio site is the bridge between design projects, career, freelance, and applications.",
    },
    {
      id: "action-dollset-case",
      actionTitle: "Write DOLLSET problem / strategy / visual system draft",
      linkedGoalId: "goal-portfolio-career",
      linkedProjectId: "project-dollset",
      area: "Creative",
      priority: "Medium",
      importance: 8,
      estimatedTime: "50 min",
      energyLevel: "high",
      dueDate: "2026-07-05",
      status: "Queued",
      whyThisMatters: "DOLLSET can become a sharp fashion branding proof piece.",
    },
    {
      id: "action-money-audit",
      actionTitle: "Mark this week's future investment spending vs wasted spending",
      linkedGoalId: "goal-study-abroad-savings",
      linkedProjectId: "",
      area: "Money",
      priority: "Medium",
      importance: 8,
      estimatedTime: "20 min",
      energyLevel: "low",
      dueDate: "2026-07-01",
      status: "Queued",
      whyThisMatters: "Money needs to support the study abroad route instead of leaking into low-return expenses.",
    },
    {
      id: "action-upwork-draft",
      actionTitle: "Draft Upwork profile headline and three service packages",
      linkedGoalId: "goal-freelance-income",
      linkedProjectId: "project-upwork-profile",
      area: "Career",
      priority: "High",
      importance: 8,
      estimatedTime: "60 min",
      energyLevel: "medium",
      dueDate: "2026-07-04",
      status: "Queued",
      whyThisMatters: "Upwork is the first overseas freelance test route.",
    },
    {
      id: "action-sns-upload",
      actionTitle: "Upload one SNS process post about DOLLSET brand rules",
      linkedGoalId: "goal-content-system",
      linkedProjectId: "project-dollset",
      area: "Content",
      priority: "Low",
      importance: 6,
      estimatedTime: "25 min",
      energyLevel: "medium",
      dueDate: "2026-07-06",
      status: "Queued",
      whyThisMatters: "Content turns portfolio process into visible career momentum.",
    },
  ],
  projects: [
    {
      id: "project-dollset",
      projectTitle: "DOLLSET",
      projectType: "Brand",
      area: "Creative",
      purpose: "Build a flash hotgirl dress brand that can become a bold fashion branding portfolio case.",
      currentProblem: "The concept must stay sharp and confident without becoming cute, princess, or coquette.",
      nextAction: "Write the case-study strategy and define the black/cherry/silver campaign rules.",
      portfolioPotential: 9,
      monetizationPotential: 7,
      careerRelevance: 8,
      linkedGoalIds: ["goal-portfolio-career", "goal-content-system"],
      relatedNotes:
        "Flash photography, chrome details, black-red palette, confident posture, no ribbon-heavy softness.",
      status: "Active",
      deadline: "2026-07-14",
    },
    {
      id: "project-nacre-room",
      projectTitle: "NACRE ROOM",
      projectType: "Brand",
      area: "Creative",
      purpose: "Create a private bridal mood total brand with nacre, quiet room, and service-system logic.",
      currentProblem: "Needs to avoid generic wedding hall, princess fantasy, and stock bridal romance.",
      nextAction: "Decode nacre material references into service, visual, and content rules.",
      portfolioPotential: 8,
      monetizationPotential: 7,
      careerRelevance: 7,
      linkedGoalIds: ["goal-portfolio-career"],
      relatedNotes:
        "Soft silver, pale blue-grey shadow, translucent veil movement, private preparation room mood.",
      status: "Planning",
      deadline: "2026-07-20",
    },
    {
      id: "project-myuve",
      projectTitle: "MYUVE",
      projectType: "Content",
      area: "Creative",
      purpose: "Develop a 5th-gen K-pop IP system that works across teaser, merch, caption, and fan memory.",
      currentProblem: "The concept risks becoming over-abstract unless every lore word becomes an asset.",
      nextAction: "List three repeatable fan-facing symbols and one merch placement rule.",
      portfolioPotential: 8,
      monetizationPotential: 6,
      careerRelevance: 8,
      linkedGoalIds: ["goal-portfolio-career"],
      relatedNotes: "Pale blue signal, chrome edge, modular symbol, fan edit continuity.",
      status: "Planning",
      deadline: "2026-08-03",
    },
    {
      id: "project-nayul-os",
      projectTitle: "NAYUL OS",
      projectType: "App",
      area: "Portfolio",
      purpose:
        "Turn personal life operations into an app case that connects goals, projects, actions, money, documents, and reviews.",
      currentProblem:
        "The app must feel like an operating system, not a productivity dashboard or a pile of CRUD forms.",
      nextAction: "Document the Goal to Action to Review flow and the mock priority/risk logic.",
      portfolioPotential: 10,
      monetizationPotential: 5,
      careerRelevance: 10,
      linkedGoalIds: ["goal-portfolio-career", "goal-germany-study"],
      relatedNotes:
        "Life HQ should summarize study, portfolio, money, career, admin, and neglected goals in one command room.",
      status: "Active",
      deadline: "2026-07-08",
    },
    {
      id: "project-portfolio-site",
      projectTitle: "Portfolio Website",
      projectType: "Portfolio",
      area: "Portfolio",
      purpose: "Publish a portfolio website that can support job applications, school review, and freelance trust.",
      currentProblem: "Needs a clear case-study order and a calm visual system that does not feel template-like.",
      nextAction: "Choose first three case studies and draft the homepage hierarchy.",
      portfolioPotential: 10,
      monetizationPotential: 6,
      careerRelevance: 10,
      linkedGoalIds: ["goal-portfolio-career", "goal-germany-study", "goal-freelance-income"],
      relatedNotes: "Include DOLLSET, NACRE ROOM, NAYUL OS, and one concise personal direction page.",
      status: "Active",
      deadline: "2026-07-21",
    },
    {
      id: "project-upwork-profile",
      projectTitle: "Upwork Profile",
      projectType: "Freelance",
      area: "Career",
      purpose: "Create an overseas freelance profile for brand identity, portfolio cleanup, and visual direction jobs.",
      currentProblem: "Need to sound specific and credible without overselling or using generic designer wording.",
      nextAction: "Write headline, overview, three services, and first proposal draft.",
      portfolioPotential: 7,
      monetizationPotential: 9,
      careerRelevance: 9,
      linkedGoalIds: ["goal-freelance-income", "goal-study-abroad-savings", "goal-portfolio-career"],
      relatedNotes:
        "Connect DOLLSET and portfolio website as proof. Emphasize brand system, moodboard decoding, and case-study structure.",
      status: "Planning",
      deadline: "2026-07-12",
    },
  ],
  studyRoutes: [
    {
      id: "study-german",
      subjectLanguage: "German A1 to B2 for study abroad",
      area: "Language",
      currentLevel: "A1 grammar and sentence order",
      targetLevel: "B2 application confidence",
      studyPurpose: "Study abroad preparation, visa confidence, and daily life readiness.",
      todaysStudyAction: "Review 30 A1 sentences and record five weak grammar patterns.",
      reviewItems: "Verb position, accusative articles, haben/sein past tense, daily routine vocabulary.",
      weakPoints: "Listening speed, article gender memory, sentence endings under pressure.",
      linkedGoalId: "goal-german-b2",
      studyStreak: 9,
      notes: "Keep the route practical: application, school, daily life, and interview sentences first.",
    },
    {
      id: "study-english",
      subjectLanguage: "English for freelance profile and interview",
      area: "Language",
      currentLevel: "Portfolio writing and interview answers",
      targetLevel: "Clear freelance proposal and confident interview explanation",
      studyPurpose: "Upwork profile, job interview, and design case-study explanation.",
      todaysStudyAction: "Rewrite Upwork headline and one service description in natural English.",
      reviewItems: "Portfolio verbs, project impact language, polite proposal structure.",
      weakPoints: "Avoiding vague phrases like creative, unique, passionate without proof.",
      linkedGoalId: "goal-freelance-income",
      studyStreak: 5,
      notes: "Use actual projects as examples instead of generic self-introduction sentences.",
    },
    {
      id: "study-chinese",
      subjectLanguage: "Chinese conversation archive",
      area: "Language",
      currentLevel: "Daily conversation archive",
      targetLevel: "Comfortable casual design and travel conversation",
      studyPurpose: "Keep conversation memory alive and collect useful phrases.",
      todaysStudyAction: "Add five phrases from recent chat and mark pronunciation weak points.",
      reviewItems: "Travel phrases, casual reactions, project introduction lines.",
      weakPoints: "Tone consistency and fast replies.",
      linkedGoalId: "goal-content-system",
      studyStreak: 3,
      notes: "Lower priority than German, but useful for content and archive personality.",
    },
  ],
  moneyRecords: [
    {
      id: "money-study-saving-1",
      recordType: "saving",
      amount: 420000,
      category: "Study abroad fund",
      connectedGoalId: "goal-study-abroad-savings",
      connectedProjectId: "",
      date: "2026-06-28",
      memo: "Monthly transfer for Germany preparation fund.",
      futureInvestment: true,
      wasted: false,
    },
    {
      id: "money-goethe-book",
      recordType: "expense",
      amount: 38000,
      category: "Language study",
      connectedGoalId: "goal-german-b2",
      connectedProjectId: "",
      date: "2026-06-26",
      memo: "German grammar workbook and vocabulary cards.",
      futureInvestment: true,
      wasted: false,
    },
    {
      id: "money-domain",
      recordType: "expense",
      amount: 21000,
      category: "Portfolio tool",
      connectedGoalId: "goal-portfolio-career",
      connectedProjectId: "project-portfolio-site",
      date: "2026-06-24",
      memo: "Domain search and portfolio site setup cost.",
      futureInvestment: true,
      wasted: false,
    },
    {
      id: "money-subscription",
      recordType: "subscription",
      amount: 14900,
      category: "Unused app subscription",
      connectedGoalId: "goal-study-abroad-savings",
      connectedProjectId: "",
      date: "2026-06-22",
      memo: "Cancel if it does not support study, design, or admin workflow this week.",
      futureInvestment: false,
      wasted: true,
    },
    {
      id: "money-upwork-income",
      recordType: "freelance",
      amount: 120000,
      category: "Freelance test income",
      connectedGoalId: "goal-freelance-income",
      connectedProjectId: "project-upwork-profile",
      date: "2026-06-21",
      memo: "Mock target income record for first overseas freelance route.",
      futureInvestment: true,
      wasted: false,
    },
  ],
  careerItems: [
    {
      id: "career-upwork",
      opportunityTitle: "Launch Upwork brand identity profile",
      type: "platform",
      companyPlatform: "Upwork",
      status: "Preparing",
      deadline: "2026-07-12",
      portfolioConnection: "DOLLSET, NACRE ROOM, Portfolio Website",
      careerRelevance: 9,
      nextAction: "Draft profile headline and three services.",
      notes: "Position as brand identity, moodboard decoding, and portfolio case-study designer.",
      linkedGoalId: "goal-freelance-income",
      linkedProjectId: "project-upwork-profile",
    },
    {
      id: "career-portfolio-site",
      opportunityTitle: "Portfolio website public version",
      type: "portfolio",
      companyPlatform: "Personal site",
      status: "Drafting",
      deadline: "2026-07-21",
      portfolioConnection: "NAYUL OS, DOLLSET, NACRE ROOM",
      careerRelevance: 10,
      nextAction: "Decide case order and write homepage direction.",
      notes: "The site should prove brand system thinking and personal OS thinking.",
      linkedGoalId: "goal-portfolio-career",
      linkedProjectId: "project-portfolio-site",
    },
    {
      id: "career-studio-job",
      opportunityTitle: "Brand studio junior designer application list",
      type: "job",
      companyPlatform: "Seoul and Berlin brand studios",
      status: "Researching",
      deadline: "2026-08-15",
      portfolioConnection: "DOLLSET for fashion, NACRE ROOM for service brand, NAYUL OS for product thinking",
      careerRelevance: 9,
      nextAction: "Collect 10 studios and mark portfolio fit.",
      notes: "Avoid companies where the visual quality is too generic or purely corporate.",
      linkedGoalId: "goal-portfolio-career",
      linkedProjectId: "project-portfolio-site",
    },
    {
      id: "career-sns",
      opportunityTitle: "SNS design process upload",
      type: "SNS",
      companyPlatform: "Instagram / Behance process post",
      status: "Preparing",
      deadline: "2026-07-06",
      portfolioConnection: "DOLLSET process and NAYUL OS workflow",
      careerRelevance: 6,
      nextAction: "Post one carousel about DOLLSET rules.",
      notes: "Make it useful, not just aesthetic.",
      linkedGoalId: "goal-content-system",
      linkedProjectId: "project-dollset",
    },
  ],
  adminItems: [
    {
      id: "admin-lmu-docs",
      itemTitle: "LMU document checklist",
      adminType: "school",
      status: "Collecting",
      deadline: "2026-07-10",
      linkedGoalId: "goal-germany-study",
      linkedProjectId: "",
      locationLink: "Local folder / Germany / LMU checklist",
      memo: "Check transcript, motivation letter requirements, language proof, and translation needs.",
    },
    {
      id: "admin-uni-assist",
      itemTitle: "uni-assist requirement page notes",
      adminType: "document",
      status: "Needed",
      deadline: "2026-07-08",
      linkedGoalId: "goal-germany-study",
      linkedProjectId: "",
      locationLink: "Browser bookmark / uni-assist notes",
      memo: "Confirm whether any document needs certified translation.",
    },
    {
      id: "admin-upwork-account",
      itemTitle: "Upwork account and payment setup",
      adminType: "account",
      status: "Needed",
      deadline: "2026-07-12",
      linkedGoalId: "goal-freelance-income",
      linkedProjectId: "project-upwork-profile",
      locationLink: "Upwork profile draft",
      memo: "Prepare profile photo, identity info, service categories, and payment method.",
    },
    {
      id: "admin-portfolio-assets",
      itemTitle: "Portfolio case image and text asset folder",
      adminType: "document",
      status: "Collecting",
      deadline: "2026-07-18",
      linkedGoalId: "goal-portfolio-career",
      linkedProjectId: "project-portfolio-site",
      locationLink: "Local folder / Portfolio / 2026 cases",
      memo: "Collect DOLLSET, NACRE ROOM, NAYUL OS, and MYUVE drafts before designing final pages.",
    },
    {
      id: "admin-health-routine",
      itemTitle: "Sleep and desk routine check",
      adminType: "health",
      status: "Waiting",
      deadline: "2026-07-07",
      linkedGoalId: "goal-germany-study",
      linkedProjectId: "",
      locationLink: "Weekly review note",
      memo: "Energy is dropping on study days. Track sleep before adding more tasks.",
    },
  ],
  weeklyReviews: [
    {
      id: "review-2026-06-30",
      weekOf: "2026-06-30",
      mostProgressedArea: "Portfolio",
      mostNeglectedArea: "Health",
      moneySummary:
        "Most spending supported future goals: German materials, portfolio domain, and study abroad savings. Cancel the unused subscription.",
      studySummary:
        "German streak is alive, but grammar correction needs more deliberate review. English should be tied to Upwork profile writing.",
      portfolioCareerSummary:
        "NAYUL OS and Portfolio Website moved forward. DOLLSET needs a clear case-study draft. Upwork profile is still waiting for a concrete headline.",
      nextWeekTopThree: [
        "Finish LMU/uni-assist document gap check.",
        "Publish the Portfolio Website first structure.",
        "Complete one German A1 correction loop and one Upwork English profile draft.",
      ],
      riskSignals:
        "German B2 progress is still low compared with the target date. Health routine is neglected and may reduce study consistency.",
      routinesToKeep: "Morning German review, Sunday money audit, Friday portfolio progress note.",
      progressUpdate:
        "This week shifted the system from isolated tasks into connected life routes: Germany, portfolio, freelance, and savings now share one map.",
    },
  ],
};
